version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Build Starting on `date`
      - npm run build
  post_build:
    commands:
      - pwd
artifacts:
  files:
    - appspec.yml
    - dist
    - package.json
  discard-paths: yes
# cache:
#   paths:
#     - '/root/.gradle/caches/**/*'
