version: 0.2

phases:
  build:
    commands:
      - echo Build Starting on `date`
      - npm run build
  post_build:
    commands:
      - pwd
artifacts:
  files:
    - appspec.yml
    - dist
  discard-paths: yes
# cache:
#   paths:
#     - '/root/.gradle/caches/**/*'
