apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-app
          image: demo-app:latest # Replace with your Docker image repo if needed
          imagePullPolicy: Never
          ports:
            - containerPort: 8080