version: '3'
services:
  app:
    restart: always
    image: <DOCKERHUB_IMAGES>
    build:
      dockerfile: Dockerfile
      context: .
    container_name: 'app'
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'

volumes:
  node_modules: