
name: Build and Deploy

on: 
  push:
      branches: [ main ]

jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Docker hub 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PW }}
    # 도커이미지 빌드, 푸시
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: <DOCKERHUB_IMAGE>