name: CD
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci

      - name: npm 빌드
        run: npm run build

      - name: zip 생성
        run: zip -r ./build.zip .
        shell: bash

      - name: AWS 설정
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3 업로드
        run: aws s3 cp --region ap-northeast-2 ./build.zip s3://aws-learner-code-deploy-bucket-haron/backend/build.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name EC2-S3-Deploy --deployment-group-name dev --s3-location bucket=aws-learner-code-deploy-bucket-haron,bundleType=zip,key=server/build.zip
